name: Deploy to Render

on:
  push:
    branches:
      - main  # change if your deploy branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optional: Build Docker image locally (to validate it builds before sending to Render)
      - name: Build Docker image
        run: docker build -t my-app .

      # Trigger Render deployment
      - name: Trigger Render Deploy
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
